### ISSUE TITLE
add aho corasick.cpp

### ISSUE THREAD

**Issue by zanpakutou** [zanpakutou/Standard#3]
##Standard code for standard algorithm :v

**Comment by rstalekar** [comment]
Hello, I would like to contribute to this project. Let me know what are the issues and features wherein I can  contribute.

**Comment by rstalekar** [comment]
Do let me know what the issue of  update in Dijkstra is? You can assign this ticket to me.

**Comment by zanpakutou** [comment]
@rstalekar  oh you can add new code for another classic algorithm ...

**Comment by zanpakutou** [comment]
@rstalekar you can add code for another classic algorithm..
